name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  LoginAcr:

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username:  ${{ secrets.ACRUSERNAME }}
        # Container registry password
        password: ${{ secrets.ACRPASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACRLOGINSERVER }}
