name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username:  ${{ secrets.ACRUSERNAME }}
        # Container registry password
        password: ${{ secrets.ACRPASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACRLOGINSERVER }}
        
    - name: Build the Docker image
      run: | 
           docker build . -t ${{ secrets.ACRLOGINSERVER }}/netapp:${{ github.sha }}
           docker push ${{ secrets.ACRLOGINSERVER }}/netapp:${{ github.sha }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
            resource-group: ${{ secrets.ACRRG }}
            dns-name-label: ${{ secrets.ACRRG }}${{ github.run_number }}
            image: ${{ secrets.ACRLOGINSERVER }}/netapp:${{ github.sha }}
            registry-login-server: ${{ secrets.ACRLOGINSERVER }}
            registry-username: ${{ secrets.ACRUSERNAME }}
            registry-password: ${{ secrets.ACRPASSWORD }}
            name: containerdemo
            location: 'francecentral'

