name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username:  ${{ secrets.ACRUSERNAME }}
        # Container registry password
        password: ${{ secrets.ACRPASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACRLOGINSERVER }}
        
    - name: Build the Docker image
      run: | 
           docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}//netapp:$(date +%s) --file Dockerfile
           docker push ${{ secrets.ACRLOGINSERVER }}/netapp:$(date +%s)



