name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    
    - name: Build and push image
      uses: Azure/docker-login@v1
      with:
        username:  ${{ secrets.ACRUSERNAME }}
        password: ${{ secrets.ACRPASSWORD }}
        login-server: ${{ secrets.ACRLOGINSERVER }}
        
    - name: Build the Docker image
      run: | 
           docker build . -t ${{ secrets.ACRLOGINSERVER }}/netapp:${{ github.sha }}
           docker push ${{ secrets.ACRLOGINSERVER }}/netapp:${{ github.sha }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
            resource-group: ${{ secrets.ACRRG }}
            dns-name-label: ${{ secrets.ACRRG }}${{ github.run_number }}
            image: ${{ secrets.ACRLOGINSERVER }}/netapp:${{ github.sha }}
            registry-login-server: ${{ secrets.ACRLOGINSERVER }}
            registry-username: ${{ secrets.ACRUSERNAME }}
            registry-password: ${{ secrets.ACRPASSWORD }}
            name: containerdemo1
            location: 'francecentral'
            cpu: 1
            memory: 1

