name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username:  HelloAcrachraf
        # Container registry password
        password: xWSgLC5P6wdJcYRaEaUynU6qQST5LD0+ 
        # Container registry server url
        login-server: helloacrachraf.azurecr.io
